#!/usr/bin/env python

import sys

from rqt_embed_window_example.embed_window_example import EmbedWindowExample
from rqt_gui.main import Main

plugin = 'rqt_embed_window_example'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
